url: https://markbrosche.github.io
remote_theme: /agency-jekyll-theme/

# Site settings
title: Mark Brosche
email: mark.brosche@gmail.com
description: "Welcome to my site."


# Team names, titles and social links
people:
- name: Mark Brosche
  pic: 1
  position: XR Engineer
  location: San Mateo, CA
  social:
    - title: linkedin
      url: "https://www.linkedin.com/in/markbrosche/"
    - title: github
      url: "https://www.github.com/MarkBrosche/"
    - title: medium
      url: "https://medium.com/@brosche"


# Build settings
markdown: kramdown
permalink: pretty