url: https://markbrosche.github.io
remote_theme: /agency-jekyll-theme/

# Site settings
title: Mark Brosche
email: mark.brosche@gmail.com
description: "Welcome to my site."


# Team names, titles and social links
people:
- name: Mark Brosche
  pic: 1
  position: XR Engineer
  location: San Francisco, CA
  social:
    - label: "Blog"
      icon: "fas fa-fw fa-link"
      url: "https://medium.com/@brosche"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/MarkBrosche"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/markbrosche/"


# Build settings
markdown: kramdown
permalink: pretty