url: https://markbrosche.github.io
remote_theme: /agency-jekyll-theme/

# Site settings
title: Mark Brosche
email: mark.brosche@gmail.com
description: "Welcome to my site."


# Team names, titles and social links
people:
- name: Mark Brosche
  pic: 1
  position: XR Engineer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll


# Build settings
markdown: kramdown
permalink: pretty